project_id = "audrvgrsuleruuspwnhf"

[functions.trigger-blog-generation]
verify_jwt = false

[functions.trigger-seo-webhook]
verify_jwt = false

[functions.update-automation-status]
verify_jwt = false

[functions.get-n8n-executions]
verify_jwt = false

[functions.get-n8n-logs]
verify_jwt = false

[functions.manage-user-roles]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.run-scheduled-seo]
verify_jwt = false

[functions.run-scheduled-blogs]
verify_jwt = false

[functions.rewrite-text]
verify_jwt = false

[functions.get-saved-hours]
verify_jwt = false

[functions.trigger-email-signature]
verify_jwt = false

[functions.trigger-add-company-webhook]
verify_jwt = false

[functions.trigger-delete-company-webhook]
verify_jwt = false
